apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-visualization
commonLabels:
  app: visualization-weavescope-frontend
  group: visualization
  env: dev

resources:
  - ../../base