apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api-asset
  name: api-asset
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/livestreamnet: "true"
        io.kompose.service: api-asset
    spec:
      containers:
      - name: api-asset
        image: registry.gviet.vn:5000/sigma-livestream/livestream-asset-management:1.0.0
        imagePullPolicy: ""
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
