apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - decorator-controller.yaml
  - deploy.yaml
  - svc.yaml
  
configMapGenerator:
  - name: service-ingress-per-pod-hooks
    files:
      # - hooks/finalize-service-per-pod.jsonnet
      - hooks/sync-ingress-per-pod.jsonnet
      - hooks/sync-node-name-as-label.jsonnet
      - hooks/sync-service-per-pod.jsonnet
      - hooks/sync-transcode-service-per-pod.jsonnet