apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: packager
spec:
  template:
    metadata:
      annotations:
        consul-svc-name: "packager"
        consul-port: "9999"
        consul-namespace: "staging-packager"
        consul-data-dir: "/data/transcode"
