apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-packager
commonLabels:
  app: packager
  group: packager
  env: staging

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
  - name: packager-config
    files:
      - data/config.json

secretGenerator:
  - name: packager-certificate
    files:
      - cert/sign.dat

resources:
  - ../../base


patchesStrategicMerge:
  - allow-schedule-on-specific-node.yaml
  - allow-create-service-per-node.yaml