apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-traefik-ingress-controller
commonLabels:
  app: traefik-ingress-controller
  group: controllers
  env: dev

resources:
  - ns.yaml
  - ../../base
