apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery-consul-server
spec:
  template:
    spec:
      containers:
        - name: consul
          volumeMounts:
            - name: data
              mountPath: /consul/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: openebs-hostpath
      resources:
        requests:
          storage: 1Gi