apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery-consul-server
spec:
  template:
    spec:
      volumes:
        - name: data
          hostPath:
            path: /usr/staging-consul-server
      containers:
        - name: consul
          volumeMounts:
            - name: data
              mountPath: /consul/data