apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-per-pod-controller
spec:
  replicas: 1
  # selector define in kustomization.yaml
  template:
    spec:
      containers:
      - name: hooks
        image: metacontroller/jsonnetd:0.1
        imagePullPolicy: Always
        workingDir: /hooks
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: service-ingress-per-pod-hooks