apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: controllers

commonLabels:
  app: service-per-pod-controller

resources:
  - decorator-controller.yaml
  - deployment.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
  - name: service-ingress-per-pod-hooks
    files:
      - hooks/finalize-service-per-pod.jsonnet
      - hooks/sync-ingress-per-pod.jsonnet
      - hooks/sync-pod-name-as-label.jsonnet
      - hooks/sync-service-per-pod.jsonnet