apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-mongo
spec:
  template:
    spec:
      containers:
        - name: mongo
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: openebs-hostpath
      resources:
        requests:
          storage: 1Gi