apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-controller
spec:
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    nodePort: 30003
    port: 8000
  - name: websecure
    protocol: TCP
    nodePort: 30004
    port: 4443
  - name: admin
    protocol: TCP
    nodePort: 30005
    port: 8080
    