apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-ingest
commonLabels:
  app: node-origin
  group: packager
  env: dev
  
configMapGenerator:
  - name: nginx-conf-template
    files:
      - nginx-conf-template/origin.conf

resources:
  - ../../base


patchesStrategicMerge:
  - allow-mount-volume-in-host.yaml
  - allow-create-ingress-per-node.yaml