apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-ingest
commonLabels:
  app: srs-origin
  group: ingest
  env: staging

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: srs-origin-conf
    files:
      - conf/srs.conf

resources:
  - ../../base

patchesStrategicMerge:
  - add-config.yaml
  - allow-schedule-on-specific-node.yaml
