apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-ingest
commonLabels:
  app: srs-ocm
  group: ingest
  env: staging

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: srs-ocm-config
    files:
      - config/staging.json

resources:
  - ../../base

patchesStrategicMerge:
  - add-config.yaml
  - allow-schedule-on-specific-node.yaml
