apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: sipp-pod-name-as-label
spec:
  hooks:
    sync:
      webhook:
        url: http://service-per-pod-controller.dev-service-per-pod-controller.svc.cluster.local/sync-pod-name-as-label

---

apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: sipp-service-per-pod
spec:
  hooks:
    sync:
      webhook:
        url: http://service-per-pod-controller.dev-service-per-pod-controller.svc.cluster.local/sync-service-per-pod

---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: sipp-ingress-per-pod
spec:
  hooks:
    sync:
      webhook:
        url: http://service-per-pod-controller.dev-service-per-pod-controller.svc.cluster.local/sync-ingress-per-pod
