apiVersion: v1
kind: ConfigMap
metadata:
  name: sc-provision-controller
data:
  storageClassMap: |     
    local-disks:
       hostDir: /mnt/local-disks
       mountDir:  /mnt/local-disks 
       blockCleanerCommand:
         - "/scripts/shred.sh"
         - "2"
       volumeMode: Filesystem
       fsType: ext4
       namePattern: "*"