apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-controllers
commonLabels:
  app: traefik-ingress-controller
  group: controllers
  env: dev

resources:
  - ../../base
  - expose-nodeport.yaml
