apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-controllers
commonLabels:
  app: metacontroller
  group: controllers
  env: staging

resources:
  - ../../base

patchesStrategicMerge:
  - allow-schedule-on-specific-node.yaml