apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs-ocm
spec:
  template:
    spec:
      containers:
        - name: srs-ocm
          env:
            - name: NODE_ENV
              value: staging
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: srs-ocm-config
