apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dev-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
# Supported policies: Delete, Retain
reclaimPolicy: Delete