apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-origin
spec:
  template:
    spec:
      containers:
        - name: origin
          volumeMounts:
            - name: statics
              mountPath: /statics
            - name: conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: statics
          hostPath:
            path: /tmp/static
        - name: conf
          configMap:
            name: node-origin-conf
