apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-origin
spec:
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  template:
    spec:
      containers:
      - name:  origin
        image:  nginx:alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  http
      restartPolicy: Always