apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-ingest
commonLabels:
  app: srs-ocm
  group: ingest
  env: dev

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
  - name: srs-ocm-config-dev
    files:
      - config/dev.json

resources:
  - ../../base

patchesStrategicMerge:
- add-dev-config.yaml
