apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs-edge  
spec:  
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - name:  srs  
        image:  ossrs/srs:3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  1935
          name: main
      restartPolicy: Always