apiVersion: v1
kind: Service
metadata:
  name: srs-edge
spec:
  type: ClusterIP
  ports:
    - name: main
      port: 1935

---
apiVersion: v1
kind: Service
metadata:
  name: srs-edge-expose
spec:
  type: NodePort
  ports:
  - name: main
    port: 1935
    nodePort: 30002