apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-packager
commonLabels:
  app: transcoder
  group: transcoder
  env: staging

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
  - name: transcoder-config
    files:
      - data/config.json

secretGenerator:
  - name: transcoder-certificate
    files:
      - cert/sign.dat

resources:
  - ../../base


patchesStrategicMerge:
  - allow-schedule-on-specific-node.yaml