apiVersion: apps/v1
kind: Deployment
metadata:
  name:  messaging-rabbitmq
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - name:  messaging-rabbitmq
        image:  rabbitmq:3.8-management
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi
        ports:
        - containerPort: 5672
          name:  main
        - containerPort: 15672
          name:  admin
      restartPolicy: Always