apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
  labels:
    io.kompose.service: packager
  name: packager
spec:
  selector:
    matchLabels:
      io.kompose.service: packager
  template:
    metadata:
      annotations:
      labels:
        io.kompose.network/livestreamnet: "true"
        io.kompose.service: packager
    spec:
      containers:
      - name: packager
        image: registry.gviet.vn:5000/sigma-livestream/transcoder:live-cpu-obf_2.0.2
        imagePullPolicy: ""
        name: packager
        resources: {}
        securityContext:
          capabilities:
            add:
            - SYS_RAWIO
        volumeMounts:
        - mountPath: /usr/transcoder/data
          name: packager-config
        - mountPath: /usr/transcoder/cert
          name: packager-certificate
        - mountPath: /data/transcoder
          name: packager-static
      restartPolicy: Always
      volumes:
        - name: packager-static
          hostPath:
            path: /tmp/static
        - name: packager-config
          configMap:
            name: packager-config
        - name: packager-certificate
          secret:
            secretName: packager-certificate        