apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-es
spec:
  serviceName: storage-es
  replicas: 3
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: storage-es
              topologyKey: kubernetes.io/hostname
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: busybox
          command: ['sysctl', '-w', 'vm.max_map_count=262144']
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ['sh', '-c', 'ulimit -n 65536']
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          env:
            - name: cluster.name
              value: storage
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: 'storage-es-0.storage-es,storage-es-1.storage-es,storage-es-2.storage-es'
            - name: cluster.initial_master_nodes
              value: 'storage-es-0,storage-es-1,storage-es-2'
            - name: ES_JAVA_OPTS
              value: '-Xms1500m -Xmx1500m'
