apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-worker
spec:
  template:
    spec:
      containers:
        - name: job-worker
          env:
          - name: NODE_ENV
            value: staging