apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs-origin
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: srs
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /usr/local/srs/conf
      volumes:
        - name: config
          configMap:
            name: srs-origin-conf
