apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-ingest
commonLabels:
  app: srs-origin
  group: ingest
  env: dev

configMapGenerator:
  - name: srs-origin-conf
    files:
      - conf/srs.conf

resources:
  - ../../base

patchesStrategicMerge:
  - add-config.yaml
