apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: storage-loki-agent
spec:
  template:
    spec:
      serviceAccountName: storage-loki-agent
      containers:
        - name: fluent-bit-loki
          volumeMounts:
            - name: run
              mountPath: /run/fluent-bit
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
      volumes:
        - name: run
          hostPath:
            path: /run/fluent-bit
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
