apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-discovery
commonLabels:
  app: discovery-consul-sync-k8s
  group: discovery
  env: staging

resources:
  - ../../base