# =================================================================
# Mongo connect information
# =================================================================
mongo:
  uri: mongodb://mongodb-headless.staging-persistence/livestream?replicaSet=rs0
# =================================================================
# Server config information
# =================================================================
server: 
  port: 80
  host: 0.0.0.0
# =================================================================
# Jobs config information
# =================================================================
job:
  types:
  - video-processing
  - stop-timeout
  lock_life_time: 15000


# =================================================================
# GRPC server information
# ================================================================= 
grpc:
  host: 0.0.0.0
  port: 50051

