apiVersion: v1
kind: Service
metadata:
  name: discovery-consul-server-dns
spec:
  ports:
    - name: dns-tcp
      port: 53
      protocol: 'TCP'
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: 'UDP'
      targetPort: dns-udp
---

apiVersion: v1
kind: Service
metadata:
  name: discovery-consul-server
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
spec:
  clusterIP: None
  # We want the servers to become available even if they're not ready
  # since this DNS is also used for join operations.
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: serflan-tcp
      protocol: 'TCP'
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: 'UDP'
      port: 8301
      targetPort: 8301
    - name: serfwan-tcp
      protocol: 'TCP'
      port: 8302
      targetPort: 8302
    - name: serfwan-udp
      protocol: 'UDP'
      port: 8302
      targetPort: 8302
    - name: server
      port: 8300
      targetPort: 8300
    - name: dns-tcp
      protocol: 'TCP'
      port: 8600
      targetPort: dns-tcp
    - name: dns-udp
      protocol: 'UDP'
      port: 8600
      targetPort: dns-udp
---
# Source: consul/templates/ui-service.yaml
# UI Service for Consul Server
apiVersion: v1
kind: Service
metadata:
  name: discovery-consul-server-ui
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8500