apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-storage
commonLabels:
  app: storage-mongo
  group: storage
  env: dev

generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../base