apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualization-kibana
spec:
  template:
    spec:
      containers:
        - name: kibana
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://storage-es.dev-storage:9200
