# =================================================================
# Mongo connect information
# =================================================================
mongo:
  uri: mongodb://mongodb-headless.staging-persistence/livestream?replicaSet=rs0
# =================================================================
# Server config information
# =================================================================
server: 
  port: 80
  host: 0.0.0.0
# =================================================================
# Consul config information
# =================================================================
consul:
  host: consul-controller-server.staging-controllers
  port: 8500


# =================================================================
# GRPC server information
# ================================================================= 
grpc:
  host: 0.0.0.0
  port: 50051

# =================================================================
# rabbit information
# ================================================================= 
rabbit:
  enabled: false