apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-livestream-channel
spec:
  template:
    spec:
      containers:
      - name: api-livestream-channel
        volumeMounts:
        - mountPath: /usr/src/app/config/config.yaml
          name: livestream-channel-config
          subPath: config.yaml
      volumes:
      - name: livestream-channel-config
        configMap:
          name: livestream-channel-config