apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-livestream-channel
spec:
  template:
    spec:
      containers:
        - name: api-livestream-channel
          env:
          - name: NODE_ENV
            value: staging