apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-ingest
commonLabels:
  app: srs
  group: ingest
  env: dev

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: srs-conf-dev
    files:
      - conf/srs.conf

resources:
  - ../../base
  - ns.yaml

patchesStrategicMerge:
  - add-dev-config.yaml
