apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-visualization
commonLabels:
  app: visualization-weavescope-frontend
  group: visualization
  env: staging

resources:
  - ../../base