apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-solution
commonLabels:
  app: api-job-worker
  group: solution-server
  env: staging

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
  - name: job-worker-config
    files:
      - config/config.yaml

resources:
  - ../../base


patchesStrategicMerge:
  - allow-schedule-on-specific-node.yaml
  - add-node-env.yaml
  - add-node-config.yaml
