apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-solution
commonLabels:
  app: api-worker
  group: solution-server
  env: staging

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
  - name: packager-config
    files:
      - data/config.json

resources:
  - ../../base


patchesStrategicMerge:
  - allow-schedule-on-specific-node.yaml