apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-controllers
commonLabels:
  app: consul-controller-sync-k8s
  group: controllers
  env: staging

resources:
  - ../../base