apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-loki
spec:
  template:
    spec:
      containers:
        - name: loki
          volumeMounts:
            - name: data
              mountPath: "/data"
      volumes:
        - name: data
          emptyDir: {}