apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-es
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: data
          hostPath:
            path: /usr/staging-es
