apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-es
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: openebs-hostpath
      resources:
        requests:
          storage: 1Gi
