apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-mongo
spec:
  serviceName: 'storage-mongo'
  replicas: 3
  template:
    metadata:
      labels:
        sidecarSelector: storage-mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:3.4.9
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: 'sidecarSelector=storage-mongo'
