apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualization-kibana
spec:
  template:
    spec:
      containers:
        - name: kibana
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://storage-es.staging-storage:9200
              
            # allow behind reverse proxy
            - name: SERVER_BASEPATH
              value: "/kibana"
            - name: SERVER_REWRITEBASEPATH
              value: "true"

