apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-visualization
commonLabels:
  app: visualization-kibana
  group: visualization
  env: staging

resources:
  - ../../base
  - ingress.yaml

patchesStrategicMerge:
  - change-es-url.yaml