apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-ingest
commonLabels:
  app: node-origin
  group: packager
  env: staging
  
configMapGenerator:
  - name: node-origin-conf
    files:
      - conf/origin.conf

resources:
  - ../../base


patchesStrategicMerge:
  - allow-mount-volume-in-host.yaml
  - allow-create-ingress-per-node.yaml
  - allow-schedule-on-specific-node.yaml