apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-controllers
commonLabels:
  app: traefik-ingress-controller
  group: controllers
  env: staging

resources:
  - ../../base
