apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-authentication
spec:
  template:
    spec:
      containers:
      - name: api-authentication
        volumeMounts:
        - mountPath: /usr/src/app/src/default/user.json
          name: api-authentication-default-value
          subPath: user.json
      volumes:
      - name: api-authentication-default-value
        configMap:
          name: api-authentication-default-value