apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-loki
spec:
  template:
    spec:
      containers:
        - name: loki
          volumeMounts:
            - name: data
              mountPath: '/data'
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: openebs-hostpath
        resources:
          requests:
            storage: 10Gi
