apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging-storage
commonLabels:
  app: storage-loki
  group: storage
  env: staging

configMapGenerator:
  - name: storage-loki
    files:
      - conf/loki.yaml

resources:
  - ../../base

patchesStrategicMerge:
  - allow-mount-data.yaml
  - allow-schedule-on-specific-node.yaml