apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-mongo-exporter
spec:
  template:
    spec:
      containers:
      - name: mongodb-exporter
        env:
          - name: MONGODB_URI
            value: "mongodb://storage-mongo.staging-storage:27017"
