apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-prometheus
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
    spec:
      serviceAccountName: monitor-prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:v2.20.1
          imagePullPolicy: IfNotPresent
          args:
            - '--storage.tsdb.retention.time=30d'
            - '--storage.tsdb.path=/prometheus'
            - '--config.file=/etc/prometheus/prometheus.yml'
          command:
            - /bin/prometheus
          ports:
            - name: web
              containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: monitor-prometheus
        - name: data
          hostPath:
            path: /tmp
            type: Directory
