apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logger-es
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: data
          emptyDir: {}