apiVersion: v1
kind: Service
metadata:
  name: srs-origin
spec:
  type: ClusterIP
  ports:
  - name: main
    port: 1935
  - name: http-api
    port: 1985

---
apiVersion: v1
kind: Service
metadata:
  name: srs-origin-expose
spec:
  type: NodePort
  ports:
  - name: main
    port: 1935
    nodePort: 30001