apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-ingest
commonLabels:
  app: node-origin
  group: packager
  env: dev

generatorOptions:
  disableNameSuffixHash: true
  
configMapGenerator:
  - name: node-package-config
    files:
      - data/config.json

resources:
  - ../../base
