apiVersion: v1
kind: Service
metadata:
  annotations:
    'consul.hashicorp.com/service-name': 'Packager'
    'consul.hashicorp.com/service-port': '9999'
    'consul.hashicorp.com/service-meta-KEY': 'value'
  name: packager
spec:
  type: ClusterIP
  ports:
  - name: rest
    port: 9999
    protocol: TCP 