apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-es-exporter
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: elasticsearch-exporter
          image: 'justwatch/elasticsearch_exporter:1.1.0'
          imagePullPolicy: IfNotPresent
          command:
            [
              'elasticsearch_exporter',
              '--log.format=logfmt',
              '--log.level=info',
              '--es.uri=http://storage-es.dev-storage:9200',
              '--es.all',
              '--es.indices',
              '--es.indices_settings',
              '--es.shards',
              '--es.snapshots',
              '--es.timeout=30s',
              '--web.listen-address=:9108',
              '--web.telemetry-path=/metrics',
            ]
          securityContext:
            capabilities:
              drop:
                - SETPCAP
                - MKNOD
                - AUDIT_WRITE
                - CHOWN
                - NET_RAW
                - DAC_OVERRIDE
                - FOWNER
                - FSETID
                - KILL
                - SETGID
                - SETUID
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - SETFCAP
            readOnlyRootFilesystem: true
          resources: {}
          ports:
            - containerPort: 9108
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 1
            timeoutSeconds: 5
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ['/bin/bash', '-c', 'sleep 20']
