apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs  
spec:  
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - name:  srs  
        image:  ossrs/srs:3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 3001
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        ports:
        - containerPort:  1935
          name: main
        - containerPort:  1985
          name:  http-api
      restartPolicy: Always