apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: visualization-grafana
spec:
  storageClassName: openebs-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi