apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-controller-sync-k8s
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "false"
    spec:
      serviceAccountName: consul-controller-sync-k8s
      containers:
        - name: consul-sync-catalog
          image: "hashicorp/consul-k8s:0.18.1"
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONSUL_HTTP_ADDR
              value: http://consul-controller-client:8500
          command:
            - "/bin/sh"
            - "-ec"
            - |
              consul-k8s sync-catalog \
                -k8s-default-sync=true \
                -consul-domain=consul \
                -allow-k8s-namespace="*" \
                -deny-k8s-namespace="kube-system" \
                -deny-k8s-namespace="kube-public" \
                -k8s-write-namespace=${NAMESPACE} \
                -node-port-sync-type=ExternalFirst \
                -log-level=info \
                -add-k8s-namespace-suffix \
          livenessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
              scheme: HTTP
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi